export default {
login: "Dragos313",
id: 50488612,
node_id: "MDQ6VXNlcjUwNDg4NjEy",
avatar_url: "https://avatars.githubusercontent.com/u/50488612?v=4",
gravatar_id: "",
url: "https://api.github.com/users/Dragos313",
html_url: "https://github.com/Dragos313",
followers_url: "https://api.github.com/users/Dragos313/followers",
following_url: "https://api.github.com/users/Dragos313/following{/other_user}",
gists_url: "https://api.github.com/users/Dragos313/gists{/gist_id}",
starred_url: "https://api.github.com/users/Dragos313/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/Dragos313/subscriptions",
organizations_url: "https://api.github.com/users/Dragos313/orgs",
repos_url: "https://api.github.com/users/Dragos313/repos",
events_url: "https://api.github.com/users/Dragos313/events{/privacy}",
received_events_url: "https://api.github.com/users/Dragos313/received_events",
type: "User",
site_admin: false,
name: "Dragos Pana",
company: null,
blog: "",
location: "Constanta, Romania",
email: null,
hireable: null,
bio: null,
twitter_username: null,
public_repos: 8,
public_gists: 0,
followers: 0,
following: 2,
created_at: "2019-05-10T12:33:12Z",
updated_at: "2021-08-08T17:27:16Z"
}